import type { Lang } from './i18n';

const vi = {
  skip: 'Bỏ qua tới nội dung',
  brandAria: 'Thaigit — trang chủ',
  navAria: 'Mục chính',
  nav: { features: 'Tính năng', guides: 'Hướng dẫn', download: 'Tải về', faq: 'Hỏi đáp' },
  headerDownload: 'Tải về',
  theme: { toLight: 'Chuyển sang giao diện sáng', toDark: 'Chuyển sang giao diện tối' },
  langSwitch: { aria: 'Đổi ngôn ngữ', title: 'English' },
  footer: {
    tagline: 'Git client trực quan, miễn phí.',
    disclaimer:
      'Thaigit là dự án độc lập. Git và tên các sản phẩm khác được nhắc tới là nhãn hiệu của chủ sở hữu tương ứng.',
    aria: 'Liên kết cuối trang',
    mac: 'Thaigit cho macOS',
    windows: 'Thaigit cho Windows',
    guides: 'Hướng dẫn Git',
    changelog: 'Nhật ký thay đổi',
    privacy: 'Quyền riêng tư',
  },
  download: {
    mac: 'Tải cho macOS',
    macFallback: 'macOS 14 trở lên · miễn phí',
    version: (version: string, size: string) => `Phiên bản ${version} · ${size}`,
    win: 'Tải cho Windows',
    winSub: 'Windows 10 / 11 · miễn phí',
    winTitle: 'Thaigit cho Windows 10 / 11',
    free: 'Tải miễn phí',
    noRelease: 'Bản phát hành đầu tiên đang được chuẩn bị.',
    released: 'Phát hành',
  },
  cta: {
    title: 'Làm việc với Git nhẹ nhàng hơn',
    text: 'Thaigit — Git client trực quan, miễn phí cho macOS và Windows.',
  },
  copy: { idle: 'Chép', done: 'Đã chép', failed: 'Hãy chép tay' },
  crumbs: { home: 'Trang chủ', aria: 'Vị trí trang' },
  compare: {
    aria: 'So sánh giao diện sáng và tối',
    valueText: (dark: number) => `Tối chiếm ${dark}%`,
    light: 'Sáng',
    dark: 'Tối',
    altLight: 'Giao diện sáng',
    altDark: 'Giao diện tối',
  },
  minutes: (n: number) => `${n} phút đọc`,
  noteLabel: { tip: 'Mẹo', warn: 'Lưu ý' },
  updated: 'Cập nhật',
  onThisPage: 'Trong bài này',
  faqTitle: 'Câu hỏi thường gặp',
  relatedGuides: 'Bài khác',
  allGuides: (n: number) => `Xem tất cả ${n} bài hướng dẫn →`,
  notFound: {
    title: 'Không tìm thấy trang',
    text: 'Trang bạn tìm không có hoặc đã được chuyển đi.',
    home: 'Về trang chủ',
  },
};

const en: typeof vi = {
  skip: 'Skip to content',
  brandAria: 'Thaigit — home',
  navAria: 'Main',
  nav: { features: 'Features', guides: 'Guides', download: 'Download', faq: 'FAQ' },
  headerDownload: 'Download',
  theme: { toLight: 'Switch to light theme', toDark: 'Switch to dark theme' },
  langSwitch: { aria: 'Change language', title: 'Tiếng Việt' },
  footer: {
    tagline: 'A visual Git client, free.',
    disclaimer:
      'Thaigit is an independent project. Git and other product names mentioned are trademarks of their respective owners.',
    aria: 'Footer links',
    mac: 'Thaigit for macOS',
    windows: 'Thaigit for Windows',
    guides: 'Git guides',
    changelog: 'Changelog',
    privacy: 'Privacy',
  },
  download: {
    mac: 'Download for macOS',
    macFallback: 'macOS 14 or later · free',
    version: (version: string, size: string) => `Version ${version} · ${size}`,
    win: 'Download for Windows',
    winSub: 'Windows 10 / 11 · free',
    winTitle: 'Thaigit for Windows 10 / 11',
    free: 'Download free',
    noRelease: 'The first release is being prepared.',
    released: 'Released',
  },
  cta: {
    title: 'Make Git a little easier today',
    text: 'Thaigit — a visual Git client, free for macOS and Windows.',
  },
  copy: { idle: 'Copy', done: 'Copied', failed: 'Copy by hand' },
  crumbs: { home: 'Home', aria: 'Breadcrumb' },
  compare: {
    aria: 'Compare light and dark themes',
    valueText: (dark: number) => `${dark}% dark`,
    light: 'Light',
    dark: 'Dark',
    altLight: 'Light theme',
    altDark: 'Dark theme',
  },
  minutes: (n: number) => `${n} min read`,
  noteLabel: { tip: 'Tip', warn: 'Heads up' },
  updated: 'Updated',
  onThisPage: 'On this page',
  faqTitle: 'Frequently asked questions',
  relatedGuides: 'More guides',
  allGuides: (n: number) => `See all ${n} guides →`,
  notFound: {
    title: 'Page not found',
    text: 'The page you are looking for does not exist or has moved.',
    home: 'Back to home',
  },
};

export const UI: Record<Lang, typeof vi> = { vi, en };
