/**
 * Chuỗi của màn Tài khoản (đăng nhập GitHub / GitLab / Bitbucket, đa tài khoản) và phần Pull Request / Merge Request.
 * Truy cập qua `vi.accounts.*` và `vi.pullRequests.*`.
 */

export const accounts = {
  title: 'Tài khoản',
  help: 'Thaigit giữ token trong kho bí mật của hệ điều hành (Keychain trên macOS, Credential Manager trên Windows) và tự dùng đúng tài khoản cho từng repo theo owner.',
  add: 'Thêm tài khoản',
  empty: 'Chưa có tài khoản nào — thêm token để fetch / pull / push không cần hỏi lại.',
  host: 'Máy chủ',
  hostPlaceholder: 'github.com',
  provider: 'Loại máy chủ',
  token: 'Personal access token',
  tokenPlaceholder: 'Dán token (repo + read:org nếu muốn chọn theo tổ chức)',
  tokenHelp: (host: string) =>
    `Tạo ở phần Settings → Developer settings của ${host}. Dán vào đây: token chỉ nằm trong kho bí mật của máy.`,
  addSubmit: 'Thêm',
  adding: 'Đang kiểm token…',
  loginByCode: 'Đăng nhập bằng mã',
  loginHelp: 'Mở trang đăng nhập, nhập mã hiện ở trên. Hết mã hoặc đóng hộp thoại thì huỷ.',
  codeLabel: 'Mã đăng nhập',
  openPage: 'Mở trang đăng nhập',
  waiting: 'Đang chờ bạn xác nhận trên trang máy chủ…',
  noClientId: 'Máy chủ chưa có Client ID của OAuth App nên chưa đăng nhập bằng mã được — hãy dán token.',
  clientId: 'Client ID của OAuth App',
  clientIdHelp: 'Người duy trì điền ở đây thì người dùng đăng nhập bằng mã được; để trống thì chỉ dán token.',
  saveClientId: 'Lưu Client ID',
  cancel: 'Huỷ',
  remove: 'Gỡ tài khoản',
  removeConfirm: (login: string) => `Gỡ ${login}? Token của tài khoản này sẽ bị xoá khỏi máy.`,
  setDefault: 'Đặt làm mặc định',
  isDefault: 'Mặc định',
  owner: 'Owner',
  ownerHelp:
    'Chọn tài khoản cho owner này (user hoặc tổ chức) — lệnh git tới repo của owner sẽ dùng tài khoản đó.',
  ownerNone: 'Tự chọn (theo tài khoản mặc định)',
  ownerForRepo: 'Tài khoản cho repo này',
  identity: 'Tên và email cho commit',
  identityHelp:
    'Dùng khi bạn gán tài khoản này cho repo: Thaigit đề nghị ghi tên / email này vào cấu hình repo.',
  identityName: 'Tên',
  identityEmail: 'Email',
  identitySave: 'Lưu',
  reasonAssigned: 'đã gán',
  reasonLogin: 'trùng tên tài khoản',
  reasonOrganization: 'thuộc tổ chức',
  reasonFallback: 'mặc định',
  organizations: 'Tổ chức / nhóm',
  repositories: 'Repo của tài khoản',
  showRepositories: 'Xem repo…',
  loadingRepositories: 'Đang tải…',
  private: 'riêng tư',
  usedAccount: (owner: string, login: string) => `Repo của ${owner} sẽ dùng tài khoản ${login}.`,
  noAccountForOwner: (owner: string) =>
    `Chưa có tài khoản nào cho ${owner} — git sẽ hỏi đăng nhập như bình thường.`,
  identityForRepo: 'Tên và email cho commit',
  identityForRepoMessage: (name: string, email: string) =>
    `Ghi "${name} <${email}>" làm tên / email commit của repo này? Commit mới sẽ được tính cho tài khoản vừa chọn.`,
  identityWrite: 'Ghi vào repo',
  identityKeep: 'Để nguyên',
  openAccounts: 'Tài khoản…',
  tokenMissing: 'Chưa có token trên máy — dán lại token của tài khoản này.',
  addedToast: (login: string) => `Đã thêm tài khoản ${login}.`,
  removedToast: (login: string) => `Đã gỡ ${login}.`,
  /** Lỗi khi gọi máy chủ (chỉ theo mã lỗi; chi tiết kỹ thuật không lên giao diện). */
  errors: {
    auth: 'Máy chủ không nhận đăng nhập — token sai, đã hết hạn hoặc thiếu quyền (hoặc kho bí mật của máy đang khoá). Đăng nhập lại tài khoản đó.',
    notFound: 'Không tìm thấy trên máy chủ — kiểm tra tên repo, hoặc tài khoản chưa có quyền với repo này.',
    network: 'Không kết nối được tới máy chủ, hoặc máy chủ đang lỗi — thử lại sau.',
    rejected: 'Máy chủ không nhận yêu cầu này.',
    busy: 'Có quá nhiều phiên đăng nhập đang mở — đóng bớt rồi thử lại.',
    invalid: 'Thông tin chưa hợp lệ — kiểm tra máy chủ, token hoặc Client ID.',
  },
} as const;

export const pullRequests = {
  section: 'PULL REQUESTS',
  noun: (count: number) => (count === 1 ? 'pull request' : 'pull requests'),
  mergeRequestNoun: (count: number) => (count === 1 ? 'merge request' : 'merge requests'),
  empty: 'Không có Pull Request nào đang mở.',
  notConnected: 'Repo chưa kết nối với máy chủ nào app nhận ra (GitHub / GitLab / Bitbucket).',
  noAccount: 'Chưa đăng nhập máy chủ này — thêm tài khoản ở Cài đặt → Tài khoản.',
  loading: 'Đang tải…',
  refresh: 'Tải lại',
  openOnWeb: 'Mở trên web',
  checkout: 'Checkout nhánh PR',
  draft: 'Nháp',
  merged: 'Đã merge',
  closed: 'Đã đóng',
  byAuthor: (author: string) => `bởi ${author}`,
  branchTo: (target: string) => `→ ${target}`,
  create: 'Tạo Pull Request',
  createFrom: (branch: string) => `Tạo Pull Request từ ${branch}`,
  title: 'Tiêu đề',
  body: 'Mô tả',
  bodyHint: 'Markdown được. Gợi ý sẽ viết từ các commit của nhánh.',
  writeWithAi: '✨ Viết mô tả bằng AI',
  writing: 'Đang viết…',
  draftRequest: 'Tạo ở dạng nháp',
  submit: 'Tạo Pull Request',
  creating: 'Đang tạo…',
  targetBranch: 'Nhánh đích',
  sourceBranch: 'Nhánh nguồn',
  sameBranch: 'Nhánh nguồn và nhánh đích phải khác nhau.',
  noBase: 'Remote chưa có nhánh nào khác để làm nhánh đích.',
  notPushed: (branch: string) => `Nhánh ${branch} chưa có trên remote — push lên trước rồi tạo Pull Request.`,
  rejected:
    'Máy chủ không nhận Pull Request — nhánh nguồn đã push chưa, hay nhánh này đã có Pull Request đang mở?',
  createdToast: (number: string) => `Đã tạo Pull Request #${number}.`,
  needsTitle: 'Tiêu đề phải có nội dung.',
} as const;
