/**
 * Chuỗi của phần AI (viết commit, giải thích commit, mô tả PR). Truy cập qua `vi.ai.*`.
 */
export const ai = {
  write: 'Viết bằng AI',
  writeTip: 'Viết commit message từ các thay đổi đã stage (Ctrl/⌘ + Shift + G)',
  stop: 'Dừng',
  regenerate: 'Tạo lại',
  undo: 'Hoàn tác',
  undoTip: 'Trả ô soạn về nội dung trước khi AI viết',
  options: 'Tuỳ chọn AI',
  writing: 'AI đang viết…',
  queued: (position: number) => `Đang chờ máy chủ AI (vị trí ${position})…`,
  remaining: (left: number) => `Còn ${left} lượt hôm nay`,

  menuLanguage: 'Ngôn ngữ',
  languageAuto: 'Tự động (theo các commit gần đây)',
  languageVi: 'Tiếng Việt',
  languageEn: 'English',
  menuLength: 'Độ dài',
  lengthShort: 'Ngắn — chỉ một dòng',
  lengthNormal: 'Vừa',
  lengthDetailed: 'Chi tiết — kèm mô tả',
  conventional: 'Conventional Commits (feat:, fix:…)',
  previewMenu: 'Xem dữ liệu sẽ gửi…',
  disable: 'Tắt AI',
  disabledToast: 'Đã tắt AI. Mã cài đặt AI trên máy này đã được xoá.',

  stageAllTitle: 'Chưa stage gì',
  stageAllMessage: 'Stage tất cả thay đổi để AI đọc và viết commit message?',
  stageAllConfirm: 'Stage tất cả & viết',
  nothingToSend: 'Chưa có thay đổi nào đã stage để AI đọc.',

  consentTitle: 'Dùng AI để viết commit?',
  consentWhat: 'Gửi gì',
  consentWhatText:
    'Các thay đổi đã stage của lần commit này, tên nhánh và tiêu đề 10 commit gần nhất (để AI viết đúng giọng của repo). Trước khi gửi, Thaigit tự bỏ file nhạy cảm (.env, khoá SSH, chứng chỉ…), lockfile, file sinh tự động, ảnh/nhị phân và mọi đoạn trông như mật khẩu, token hay khoá.',
  consentWhere: 'Gửi đi đâu',
  consentWhereText:
    'Tới máy chủ Thaigit do tác giả Thaigit vận hành. Model AI (Hermes) chạy ngay trên máy chủ đó — không gửi cho bên thứ ba, không lưu nội dung. Máy chủ chỉ giữ số liệu kỹ thuật (số token, thời gian, mã lỗi) trong 30 ngày.',
  consentLimits: 'Giới hạn',
  consentLimitsText:
    'Miễn phí, mỗi máy có số lượt nhất định mỗi ngày. Chỉ gửi khi bạn bấm nút AI. Tắt bất cứ lúc nào trong menu Tuỳ chọn AI.',
  consentPreview: 'Xem dữ liệu sẽ gửi',
  consentHidePreview: 'Ẩn dữ liệu',
  consentAccept: 'Đồng ý & viết',
  cancel: 'Huỷ',

  previewTitle: 'Dữ liệu sẽ gửi cho AI',
  previewSent: (count: number) => `Gửi nội dung ${count} file`,
  previewSkipped: (count: number) => `Chỉ gửi tên ${count} file`,
  previewRedacted: (count: number) => `Đã bỏ ${count} đoạn có thể chứa bí mật`,
  previewTruncated: 'đã rút gọn',
  previewStatus: {
    added: 'mới',
    modified: 'sửa',
    deleted: 'xoá',
    renamed: 'đổi tên',
    copied: 'chép',
    typechange: 'đổi kiểu',
  } as Record<string, string>,
  previewSubjects: 'Tiêu đề commit gần đây',
  previewBranch: (branch: string) => `Nhánh: ${branch}`,
  previewClose: 'Đóng',
  skipReason: {
    lockfile: 'lockfile',
    generated: 'file sinh tự động',
    binary: 'nhị phân / ảnh',
    sensitive: 'file nhạy cảm',
    secret: 'có thể chứa bí mật',
    undecodable: 'không phải UTF-8',
    budget: 'quá dài',
  } as Record<string, string>,

  explain: 'Giải thích bằng AI',
  explainTitle: 'AI giải thích commit',
  explainTip: 'Tóm tắt, thay đổi chính và rủi ro của commit này',
  prDescription: 'Viết mô tả PR với AI…',
  prTitle: (head: string) => `Mô tả Pull Request cho ${head}`,
  prBaseTitle: 'Viết mô tả Pull Request',
  prBaseMessage: (head: string) => `AI đọc các commit và thay đổi của ${head} so với nhánh đích.`,
  prBaseLabel: 'Nhánh đích',
  prBaseConfirm: 'Viết mô tả',
  prNoChanges: 'Nhánh này không có thay đổi nào so với nhánh đích.',
  copy: 'Sao chép',
  copied: 'Đã sao chép',
  close: 'Đóng',

  errors: {
    title: 'AI chưa viết được',
    quota_exhausted: 'Hết lượt AI hôm nay — lượt mới có lúc 0:00 (giờ Việt Nam).',
    ip_rate_limited: (seconds: number) => `Bạn dùng AI hơi nhanh — thử lại sau ${seconds} giây.`,
    ai_busy: (seconds: number) => `Máy chủ AI đang bận — thử lại sau ${seconds} giây.`,
    ai_unavailable: 'Máy chủ AI đang tạm ngừng — thử lại sau.',
    ai_disabled: 'AI đang tạm tắt trên máy chủ — thử lại sau.',
    too_large: 'Thay đổi quá lớn để AI đọc — stage bớt rồi thử lại.',
    invalid_token: 'Không xác thực được với máy chủ AI — thử lại sau.',
    server: 'Máy chủ AI không xử lý được yêu cầu — thử lại sau.',
    network: 'Không kết nối được máy chủ AI — kiểm tra mạng rồi thử lại.',
    empty: 'AI không trả lời gì — bấm Tạo lại để thử lần nữa.',
  },
} as const;
