/**
 * Chuỗi của phần nhánh / tag / stash / merge-rebase / xung đột / menu ngữ cảnh. Truy cập qua `vi.branches.*`. Văn phong bám
 * theo app Swift (RepoModel+Actions).
 */
export const branches = {
  // Checkout
  checkout: 'Checkout',
  checkoutTitle: (target: string) => `Checkout ${target}`,
  alreadyOn: (branch: string) => `Đang ở nhánh ${branch}`,
  switched: (branch: string) => `Đã chuyển sang nhánh ${branch}`,
  trackingCreated: (local: string, remote: string) => `Đã tạo nhánh ${local} theo dõi ${remote}`,
  tagLabel: (tag: string) => `tag ${tag}`,

  // Hộp "Chuyển nhánh" (Ctrl/⌘ + B)
  pickerTitle: 'Chuyển nhánh',
  pickerOpen: 'Tìm & chuyển nhánh…',
  pickerShortcut: 'Ctrl/⌘ + B',
  pickerPlaceholder: 'Gõ tên nhánh…',
  pickerRecent: 'Nhánh gần đây',
  pickerHint: '↑↓ chọn · Enter checkout · Esc đóng',
  pickerEmpty: 'Không có nhánh khớp',
  pickerCurrent: 'Hiện tại',
  pickerRemote: 'Remote',
  detachedConfirmTitle: (label: string) => `Checkout ${label}?`,
  detachedConfirmMessage:
    'Bạn sẽ ở trạng thái detached HEAD (không thuộc nhánh nào). Muốn commit tiếp thì hãy tạo nhánh mới tại đó.',
  detached: (label: string) => `Đang ở ${label} (detached HEAD)`,
  undoCheckout: 'Hoàn tác checkout',
  autoStashMessage: (title: string) => `Thaigit: tự stash trước khi ${title.toLowerCase()}`,
  carriedChanges: (title: string) => `${title} xong — đã mang theo thay đổi chưa commit`,
  carryConflict: (title: string) => `${title} xong, nhưng thay đổi chưa commit bị xung đột với nhánh mới`,
  carryConflictMessage:
    'Thay đổi gốc vẫn được giữ trong stash mới nhất — giải quyết xung đột hoặc pop lại sau.',
  showChanges: 'Xem thay đổi',

  // Tạo nhánh
  createTitle: 'Tạo nhánh mới',
  createTitleNamed: (name: string) => `Tạo nhánh ${name}`,
  createMessage: (start: string) => `Nhánh mới bắt đầu từ ${start}.`,
  create: 'Tạo nhánh',
  nameLabel: 'Tên nhánh',
  checkoutAfterCreate: 'Chuyển sang nhánh mới',
  nameRequired: 'Nhập tên nhánh',
  nameInvalid: 'Tên nhánh không hợp lệ (không dấu cách, không ~ ^ : ? * [ \\, không “..”)',
  nameExists: (name: string) => `Đã có nhánh ${name}`,
  needCommitFirst: 'Cần có ít nhất một commit trước khi tạo nhánh',
  created: (name: string) => `Đã tạo nhánh ${name}`,
  createdAndSwitched: (name: string) => `Đã tạo và chuyển sang nhánh ${name}`,
  deleteTitle: (name: string) => `Xoá nhánh ${name}`,

  // Stash
  stashTitle: 'Stash',
  stashed: 'Đã stash thay đổi',
  nothingToStash: 'Không có thay đổi nào để stash',
  noStash: 'Không có stash nào',
  popTitle: 'Pop stash',
  popped: 'Đã pop thay đổi từ stash',
  stashKept: 'Stash vẫn được giữ lại vì có xung đột',
  applyStashTitle: 'Apply stash',
  stashApplied: (label: string) => `Đã apply stash “${label}”`,
  dropStash: 'Xoá stash',
  dropStashConfirmTitle: (label: string) => `Xoá stash “${label}”?`,
  stashDropped: 'Đã xoá stash',
  restoreStash: 'Khôi phục stash',
  undoHint: 'Có thể bấm “Hoàn tác” ngay sau đó.',
  stashWithMessage: 'Stash kèm message…',
  stashMessageTitle: 'Stash thay đổi',
  stashMessageLabel: 'Message (tuỳ chọn)',
  stashIncludeUntracked: 'Gồm cả file mới (chưa track)',
  stashApplyKeep: 'Apply (giữ stash)',
  stashPopDrop: 'Pop (apply rồi xoá stash)',
  dropStashMenu: 'Xoá stash…',

  // Xoá / đổi tên nhánh
  cannotDeleteCurrent: 'Không thể xoá nhánh đang checkout — hãy chuyển sang nhánh khác trước',
  deleteConfirmTitle: (name: string) => `Xoá nhánh “${name}”?`,
  deleteConfirmMessage: 'Chỉ xoá nhánh trên máy bạn. Có thể bấm “Hoàn tác” ngay sau đó.',
  deleteBranch: 'Xoá nhánh',
  deleted: (name: string) => `Đã xoá nhánh ${name}`,
  restoreBranch: (name: string) => `Khôi phục nhánh ${name}`,
  notMerged: (name: string) => `Nhánh ${name} có commit chưa được merge`,
  deleteAnyway: 'Vẫn xoá',
  deleteRemoteConfirmTitle: (name: string) => `Xoá nhánh “${name}” trên remote?`,
  deleteRemoteConfirmMessage: (branch: string, remote: string) =>
    `Nhánh ${branch} sẽ bị xoá khỏi ${remote} cho mọi người.`,
  deleteOnRemote: 'Xoá trên remote',
  deleteRemoteTitle: (name: string) => `Xoá ${name}`,
  deletedRemote: (name: string) => `Đã xoá ${name}`,
  restoreRemote: (name: string) => `Khôi phục ${name}`,
  renameTitle: (name: string) => `Đổi tên nhánh ${name}`,
  renameLabel: 'Tên mới',
  rename: 'Đổi tên',
  renameRunning: 'Đổi tên nhánh',
  renamed: (oldName: string, newName: string) => `Đã đổi tên ${oldName} → ${newName}`,
  fastForwardTitle: (name: string) => `Fast-forward ${name}`,
  fastForwarded: (name: string) => `Đã fast-forward ${name}`,

  // Merge / rebase / cherry-pick / revert / reset
  needBranchToMerge: 'Cần đứng trên một nhánh để merge',
  mergeTitle: (source: string, target: string) => `Merge ${source} vào ${target}`,
  merged: (source: string, target: string) => `Đã merge ${source} vào ${target}`,
  undoMerge: 'Hoàn tác merge',
  needBranchToRebase: 'Cần đứng trên một nhánh để rebase',
  rebaseConfirmTitle: (branch: string, onto: string) => `Rebase ${branch} lên ${onto}?`,
  rebaseConfirmMessage: (branch: string, onto: string) =>
    `Các commit riêng của ${branch} sẽ được viết lại lên trên ${onto}. Tránh rebase nhánh đã push mà người khác đang dùng.`,
  rebase: 'Rebase',
  rebaseTitle: (branch: string, onto: string) => `Rebase ${branch} lên ${onto}`,
  rebased: (branch: string, onto: string) => `Đã rebase ${branch} lên ${onto}`,
  undoRebase: 'Hoàn tác rebase',
  cherryPickTitle: (sha: string) => `Cherry-pick ${sha}`,
  cherryPicked: (subject: string) => `Đã cherry-pick “${subject}”`,
  undoCherryPick: 'Hoàn tác cherry-pick',
  revertConfirmTitle: (subject: string) => `Revert commit “${subject}”?`,
  revertConfirmMessage: (branch: string, sha: string) =>
    `Tạo một commit mới trên ${branch} đảo ngược thay đổi của ${sha}. Lịch sử cũ giữ nguyên.`,
  revertMergeNote: (parent: string) =>
    `Đây là merge commit: thay đổi được đảo ngược so với parent đầu tiên (${parent}).`,
  revertNoCommitNote:
    '“Revert, chưa commit” chỉ stage thay đổi đảo ngược để bạn xem lại hoặc sửa trước khi tự commit.',
  revertAndCommit: 'Revert & commit',
  revertNoCommit: 'Revert, chưa commit',
  revertTitle: (sha: string) => `Revert ${sha}`,
  revertNoCommitTitle: (sha: string) => `Revert ${sha} (chưa commit)`,
  reverted: (subject: string) => `Đã tạo commit revert “${subject}”`,
  revertedNoCommit: (subject: string) => `Đã revert “${subject}” — chưa commit`,
  revertBlockedByStaged: 'Revert bị chặn vì có thay đổi đã stage',
  revertBlockedMessage: 'Commit hoặc stash chúng trước, nếu không chúng sẽ lẫn vào commit revert.',
  undoRevert: 'Hoàn tác revert',
  resetTitle: (branch: string, mode: string) => `Reset ${branch} (${mode})`,
  resetDone: (branch: string, sha: string) => `Đã reset ${branch} về ${sha}`,
  undoReset: 'Hoàn tác reset',
  resetHardConfirmTitle: (branch: string, sha: string) => `Hard reset ${branch} về ${sha}?`,
  resetHardConfirmMessage: (sha: string) =>
    `Mọi thay đổi chưa commit sẽ MẤT VĨNH VIỄN. Các commit sau ${sha} sẽ không còn trên nhánh (vẫn hoàn tác được ngay sau đó).`,
  resetHard: 'Hard reset',
  resetSoft: 'Soft — giữ mọi thay đổi ở trạng thái đã stage',
  resetMixed: 'Mixed — giữ thay đổi, bỏ stage',
  resetHardMenu: 'Hard — bỏ mọi thay đổi',
  discardAllConfirmTitle: 'Huỷ TẤT CẢ thay đổi chưa commit?',
  discardAllConfirmMessage:
    'Mọi thay đổi (kể cả đã stage) sẽ bị bỏ, file chưa track được dời vào thùng rác của Thaigit. Có thể bấm “Hoàn tác” ngay sau đó.',
  discardAll: 'Huỷ tất cả',
  discardAllTitle: 'Huỷ tất cả thay đổi',
  discardedAll: 'Đã huỷ tất cả thay đổi',
  undoDiscardAll: 'Hoàn tác huỷ tất cả',
  useOperationBanner: (title: string) => `${title} — hãy dùng nút “Huỷ” trên thanh trạng thái thao tác`,
  ignoreTitle: 'Thêm vào .gitignore',
  ignored: (pattern: string) => `Đã thêm “${pattern}” vào .gitignore`,

  // Thao tác dở dang (banner)
  running: {
    merging: 'Đang merge',
    rebasing: 'Đang rebase',
    cherryPicking: 'Đang cherry-pick',
    reverting: 'Đang revert',
    applyingPatches: 'Đang áp dụng patch (git am)',
    bisecting: 'Đang bisect',
  },
  runningRebaseStep: (step: number, total: number) => `Đang rebase (${step}/${total})`,
  continueOperation: 'Tiếp tục',
  skipOperation: 'Bỏ qua commit này',
  abortOperation: 'Huỷ',
  continueTitle: (name: string) => `Tiếp tục ${name}`,
  continued: 'Đã tiếp tục',
  conflictsLeft: (count: number) => `Còn ${count} file xung đột chưa giải quyết`,
  abortConfirmTitle: (name: string) => `Huỷ ${name}?`,
  abortConfirmMessage: (name: string) => `Repository sẽ quay về trạng thái trước khi bắt đầu ${name}.`,
  abortTitle: (name: string) => `Huỷ ${name}`,
  aborted: (name: string) => `Đã huỷ ${name}`,
  skipTitle: 'Bỏ qua commit hiện tại',

  // Tag
  createTagTitle: 'Tạo tag',
  createTagMessage: (label: string) => `Tag gắn vào commit ${label}.`,
  tagNameLabel: 'Tên tag',
  tagMessageLabel: 'Message (nếu có sẽ tạo annotated tag)',
  tagPushToRemote: (remote: string) => `Push tag lên ${remote}`,
  createTag: 'Tạo tag',
  tagNameRequired: 'Nhập tên tag',
  tagNameInvalid: 'Tên tag không hợp lệ',
  tagExists: (name: string) => `Đã có tag ${name}`,
  createTagRunning: (name: string) => `Tạo tag ${name}`,
  tagCreated: (name: string) => `Đã tạo tag ${name}`,
  tagCreatedPushed: (name: string) => `Đã tạo và push tag ${name}`,
  deleteTagConfirmTitle: (name: string) => `Xoá tag “${name}”?`,
  deleteTagConfirmMessage: 'Chỉ xoá tag trên máy bạn. Có thể bấm “Hoàn tác” ngay sau đó.',
  deleteTag: 'Xoá tag',
  deleteTagRunning: (name: string) => `Xoá tag ${name}`,
  tagDeleted: (name: string) => `Đã xoá tag ${name}`,
  restoreTag: 'Khôi phục tag',
  pushTagRunning: (name: string) => `Push tag ${name}`,
  tagPushed: (name: string, remote: string) => `Đã push tag ${name} lên ${remote}`,
  deleteRemoteTagConfirmTitle: (name: string, remote: string) => `Xoá tag “${name}” trên ${remote}?`,
  deleteRemoteTagConfirmMessage: 'Tag sẽ bị xoá khỏi remote cho mọi người; tag trên máy bạn vẫn giữ nguyên.',
  deleteRemoteTagRunning: 'Xoá tag trên remote',
  remoteTagDeleted: (name: string, remote: string) => `Đã xoá tag ${name} trên ${remote}`,

  // Giải xung đột
  conflictBlocks: (count: number) => `${count} đoạn xung đột`,
  conflictLegend: '“Current” là bản trên nhánh hiện tại (HEAD), “Incoming” là bản đang được đưa vào.',
  conflictLineHint: 'Bấm vào từng dòng để chọn riêng dòng đó; nhấp đúp tiêu đề một bên để giữ cả bên đó.',
  prevConflict: 'Đoạn xung đột trước (Alt + ↑)',
  nextConflict: 'Đoạn xung đột sau (Alt + ↓)',
  conflictPosition: (index: number, total: number) => `${index}/${total}`,
  quickPick: 'Chọn nhanh',
  fillCurrent: 'Mọi đoạn chưa chọn: giữ Current',
  fillIncoming: 'Mọi đoạn chưa chọn: giữ Incoming',
  fillBoth: 'Mọi đoạn chưa chọn: giữ cả hai',
  keepWholeSide: (side: string) => `Nhấp đúp để giữ cả bản ${side}`,
  outputLeft: (count: number) => `còn ${count} đoạn chưa chọn`,
  editOutput: 'Sửa tay',
  editOutputTip: 'Sửa trực tiếp nội dung sẽ được lưu',
  editingOutput: 'Đang sửa tay kết quả',
  markersLeftTitle: 'Kết quả vẫn còn dấu xung đột',
  markersLeftMessage:
    'Trong khung Kết quả còn dòng <<<<<<< / ======= / >>>>>>>. Lưu như vậy thì file vẫn chứa dấu xung đột.',
  saveAnyway: 'Vẫn lưu',
  conflictCount: (count: number) => `${count} đoạn`,
  resolveAll: 'Giải quyết tất cả',
  resolveSelected: (count: number) => `Giải quyết ${count} file`,
  resolveAllTip: 'Dùng nguyên bản một bên cho nhiều file một lần — Ctrl-click để chọn từng file',
  useCurrentFor: (count: number) => `Dùng bản Current cho ${count} file`,
  useIncomingFor: (count: number) => `Dùng bản Incoming cho ${count} file`,
  resolvedMany: (count: number) => `Đã giải quyết ${count} file`,
  useAllCurrent: 'Dùng toàn bộ Current',
  useAllIncoming: 'Dùng toàn bộ Incoming',
  useCurrentRunning: 'Dùng bản Current',
  useIncomingRunning: 'Dùng bản Incoming',
  conflictResolved: (name: string) => `Đã giải quyết ${name}`,
  conflictNumber: (index: number, total: number) => `Xung đột ${index}/${total}`,
  conflictChosen: 'Đã chọn',
  keepCurrent: 'Giữ Current',
  keepIncoming: 'Giữ Incoming',
  keepBoth: 'Giữ cả hai',
  keepBothIncomingFirst: 'Cả hai (Incoming trước)',
  keepBase: 'Bản gốc (base)',
  keepNeither: 'Bỏ cả hai',
  clearChoice: 'Bỏ chọn',
  moreChoices: 'Lựa chọn khác',
  current: 'Current',
  incoming: 'Incoming',
  result: 'Kết quả',
  resultEmpty: '(trống — đoạn này sẽ bị xoá)',
  unchangedLines: (count: number) => `… ${count} dòng không đổi — bấm để xem`,
  chosenCount: (chosen: number, total: number) => `Đã chọn ${chosen}/${total}`,
  resetChoices: 'Chọn lại',
  saveResolution: 'Lưu & đánh dấu đã giải quyết',
  saveResolutionRunning: 'Lưu file đã giải quyết',
  unresolvedBlocks: 'Còn xung đột chưa chọn cách giải quyết',
  changedOnDisk: 'File đã bị sửa bên ngoài — đã nạp lại, hãy chọn lại',
  markResolved: 'Đánh dấu đã giải quyết',
  markResolvedRunning: 'Đánh dấu đã giải quyết',
  wholeFileOnly: (description: string) => `${description} — chỉ chọn được cả file.`,
  notUtf8:
    'File không phải UTF-8 nên không giải từng đoạn trong app được. Chọn cả file, hoặc sửa bằng trình soạn thảo rồi bấm “Đánh dấu đã giải quyết”.',
  openConflict: 'Giải xung đột',
  conflictKinds: {
    bothModified: 'Cả hai bên đều sửa',
    bothAdded: 'Cả hai bên đều thêm',
    deletedByUs: 'Bên hiện tại đã xoá',
    deletedByThem: 'Bên kia đã xoá',
    addedByUs: 'Bên hiện tại thêm',
    addedByThem: 'Bên kia thêm',
    bothDeleted: 'Cả hai bên đều xoá',
    unknown: 'Xung đột',
  },

  // Menu ngữ cảnh
  menuPull: 'Pull',
  menuPush: 'Push',
  menuCheckout: (name: string) => `Checkout ${name}`,
  menuMergeInto: (source: string, target: string) => `Merge ${source} vào ${target}`,
  menuRebaseOnto: (branch: string, onto: string) => `Rebase ${branch} lên ${onto}`,
  menuPushBranch: (name: string) => `Push ${name}`,
  menuFastForward: (upstream: string) => `Fast-forward theo ${upstream}`,
  menuCreateBranchFrom: (name: string) => `Tạo nhánh từ ${name}…`,
  menuRename: 'Đổi tên…',
  menuDeleteBranch: 'Xoá nhánh…',
  menuDeleteOnRemote: 'Xoá trên remote…',
  menuCheckoutTag: (name: string) => `Checkout tag ${name}`,
  menuPushTag: 'Push tag lên remote',
  menuCreateBranchFromTag: 'Tạo nhánh từ tag…',
  menuDeleteTag: 'Xoá tag…',
  menuDeleteRemoteTag: 'Xoá tag trên remote…',
  menuCopyName: 'Sao chép tên',
  copyNameLabel: 'tên',
  menuCreateBranchHere: 'Tạo nhánh tại đây…',
  menuCreateTagHere: 'Tạo tag tại đây…',
  menuCheckoutCommit: 'Checkout commit này',
  commitLabel: (sha: string) => `commit ${sha}`,
  menuCherryPick: (branch: string) => `Cherry-pick vào ${branch}`,
  menuRevert: 'Revert commit này…',
  menuReset: (branch: string) => `Reset ${branch} về đây`,
  menuCopySha: 'Sao chép SHA',
  menuCopyMessage: 'Sao chép message',
  copyMessageLabel: 'message',
  menuStageAll: 'Stage tất cả',
  menuUnstageAll: 'Bỏ stage tất cả',
  menuStashAll: 'Stash tất cả thay đổi',
  menuDiscardAll: 'Huỷ tất cả thay đổi…',
  menuStageFile: 'Stage file',
  menuUnstageFile: 'Bỏ stage file',
  menuDiscardFile: 'Huỷ thay đổi…',
  menuIgnore: 'Thêm vào .gitignore',
  menuIgnoreFile: 'Bỏ qua file này',
  menuIgnoreExtension: (ext: string) => `Bỏ qua mọi file *.${ext}`,
  menuIgnoreFolder: (folder: string) => `Bỏ qua thư mục ${folder}/`,
  menuOpenDiff: 'Xem diff',
  menuCopyPath: 'Sao chép đường dẫn',
  copyPathLabel: 'đường dẫn',
  menuOpenInEditor: 'Mở bằng trình soạn thảo',
  menuReveal: 'Hiện trong thư mục',
  menuOpenTerminal: 'Mở Terminal tại repo',
  menuOpenRepoInEditor: 'Mở repo bằng trình soạn thảo',
  menuRevealRepo: 'Mở thư mục repo',
  osFailed: 'Không mở được ứng dụng',
} as const;
