/** Bản tiếng Anh của `branches.vi.ts` (cùng khoá, cùng tham số). */
import type { branches as source } from './branches.vi.ts';
import type { Translation } from './types.ts';

export const branches: Translation<typeof source> = {
  checkout: 'Checkout',
  checkoutTitle: (target: string) => `Checkout ${target}`,
  alreadyOn: (branch: string) => `Already on branch ${branch}`,
  switched: (branch: string) => `Switched to branch ${branch}`,
  trackingCreated: (local: string, remote: string) => `Created branch ${local} tracking ${remote}`,
  tagLabel: (tag: string) => `tag ${tag}`,

  pickerTitle: 'Switch branch',
  pickerOpen: 'Find & switch branch…',
  pickerShortcut: 'Ctrl/⌘ + B',
  pickerPlaceholder: 'Type a branch name…',
  pickerRecent: 'Recent branches',
  pickerHint: '↑↓ select · Enter checkout · Esc close',
  pickerEmpty: 'No matching branches',
  pickerCurrent: 'Current',
  pickerRemote: 'Remote',
  detachedConfirmTitle: (label: string) => `Checkout ${label}?`,
  detachedConfirmMessage:
    'You will be in “detached HEAD” mode (not on any branch). To keep committing, create a new branch there.',
  detached: (label: string) => `On ${label} (detached HEAD)`,
  undoCheckout: 'Undo checkout',
  checkoutBlocked: "Can't checkout because of uncommitted changes",
  stashAndCheckout: 'Stash and checkout',
  autoStashMessage: (title: string) => `Thaigit: auto-stash before ${title.toLowerCase()}`,
  doneWithStash: (title: string) => `${title} done — your changes were saved to a stash`,
  popStash: 'Pop stash',

  createTitle: 'New branch',
  createTitleNamed: (name: string) => `Create branch ${name}`,
  createMessage: (start: string) => `The new branch starts at ${start}.`,
  create: 'Create branch',
  nameLabel: 'Branch name',
  checkoutAfterCreate: 'Switch to the new branch',
  nameRequired: 'Enter a branch name',
  nameInvalid: 'Invalid branch name (no spaces, no ~ ^ : ? * [ \\, no “..”)',
  nameExists: (name: string) => `Branch ${name} already exists`,
  needCommitFirst: 'You need at least one commit before creating a branch',
  created: (name: string) => `Created branch ${name}`,
  createdAndSwitched: (name: string) => `Created and switched to branch ${name}`,
  deleteTitle: (name: string) => `Delete branch ${name}`,

  stashTitle: 'Stash',
  stashed: 'Changes saved to a stash',
  nothingToStash: 'No changes to stash',
  noStash: 'No stashes',
  popTitle: 'Pop stash',
  popped: 'Changes restored from the stash',
  stashKept: 'The stash was kept because of conflicts',
  applyStashTitle: 'Apply stash',
  stashApplied: (label: string) => `Applied stash “${label}”`,
  dropStash: 'Drop stash',
  dropStashConfirmTitle: (label: string) => `Drop stash “${label}”?`,
  stashDropped: 'Stash dropped',
  restoreStash: 'Restore stash',
  undoHint: 'You can click “Undo” right after.',
  stashWithMessage: 'Stash with message…',
  stashMessageTitle: 'Stash changes',
  stashMessageLabel: 'Message (optional)',
  stashIncludeUntracked: 'Include new (untracked) files',
  stashApplyKeep: 'Apply (keep stash)',
  stashPopDrop: 'Pop (apply, then drop)',
  dropStashMenu: 'Drop stash…',

  cannotDeleteCurrent: "Can't delete the checked-out branch — switch to another branch first",
  deleteConfirmTitle: (name: string) => `Delete branch “${name}”?`,
  deleteConfirmMessage: 'Only deletes the branch on your computer. You can click “Undo” right after.',
  deleteBranch: 'Delete branch',
  deleted: (name: string) => `Deleted branch ${name}`,
  restoreBranch: (name: string) => `Restore branch ${name}`,
  notMerged: (name: string) => `Branch ${name} has commits that are not merged`,
  deleteAnyway: 'Delete anyway',
  deleteRemoteConfirmTitle: (name: string) => `Delete branch “${name}” on the remote?`,
  deleteRemoteConfirmMessage: (branch: string, remote: string) =>
    `Branch ${branch} will be deleted from ${remote} for everyone.`,
  deleteOnRemote: 'Delete on remote',
  deleteRemoteTitle: (name: string) => `Delete ${name}`,
  deletedRemote: (name: string) => `Deleted ${name}`,
  restoreRemote: (name: string) => `Restore ${name}`,
  renameTitle: (name: string) => `Rename branch ${name}`,
  renameLabel: 'New name',
  rename: 'Rename',
  renameRunning: 'Rename branch',
  renamed: (oldName: string, newName: string) => `Renamed ${oldName} → ${newName}`,
  fastForwardTitle: (name: string) => `Fast-forward ${name}`,
  fastForwarded: (name: string) => `Fast-forwarded ${name}`,

  needBranchToMerge: 'You need to be on a branch to merge',
  mergeTitle: (source: string, target: string) => `Merge ${source} into ${target}`,
  merged: (source: string, target: string) => `Merged ${source} into ${target}`,
  undoMerge: 'Undo merge',
  needBranchToRebase: 'You need to be on a branch to rebase',
  rebaseConfirmTitle: (branch: string, onto: string) => `Rebase ${branch} onto ${onto}?`,
  rebaseConfirmMessage: (branch: string, onto: string) =>
    `The commits only on ${branch} will be rewritten on top of ${onto}. Avoid rebasing a pushed branch that others are using.`,
  rebase: 'Rebase',
  rebaseTitle: (branch: string, onto: string) => `Rebase ${branch} onto ${onto}`,
  rebased: (branch: string, onto: string) => `Rebased ${branch} onto ${onto}`,
  undoRebase: 'Undo rebase',
  cherryPickTitle: (sha: string) => `Cherry-pick ${sha}`,
  cherryPicked: (subject: string) => `Cherry-picked “${subject}”`,
  undoCherryPick: 'Undo cherry-pick',
  revertConfirmTitle: (subject: string) => `Revert commit “${subject}”?`,
  revertConfirmMessage: (branch: string, sha: string) =>
    `Creates a new commit on ${branch} that reverses the changes of ${sha}. Existing history stays the same.`,
  revertMergeNote: (parent: string) =>
    `This is a merge commit: the changes are reversed relative to the first parent (${parent}).`,
  revertNoCommitNote:
    '“Revert without committing” only stages the reversed changes so you can review or edit them before committing yourself.',
  revertAndCommit: 'Revert & commit',
  revertNoCommit: 'Revert without committing',
  revertTitle: (sha: string) => `Revert ${sha}`,
  revertNoCommitTitle: (sha: string) => `Revert ${sha} (not committed)`,
  reverted: (subject: string) => `Created revert commit “${subject}”`,
  revertedNoCommit: (subject: string) => `Reverted “${subject}” — not committed yet`,
  revertBlockedByStaged: 'Revert is blocked because there are staged changes',
  revertBlockedMessage: 'Commit or stash them first, otherwise they would end up in the revert commit.',
  undoRevert: 'Undo revert',
  resetTitle: (branch: string, mode: string) => `Reset ${branch} (${mode})`,
  resetDone: (branch: string, sha: string) => `Reset ${branch} to ${sha}`,
  undoReset: 'Undo reset',
  resetHardConfirmTitle: (branch: string, sha: string) => `Hard reset ${branch} to ${sha}?`,
  resetHardConfirmMessage: (sha: string) =>
    `All uncommitted changes will be LOST FOREVER. Commits after ${sha} will no longer be on the branch (you can still undo right after).`,
  resetHard: 'Hard reset',
  resetSoft: 'Soft — keep all changes as staged',
  resetMixed: 'Mixed — keep changes, unstaged',
  resetHardMenu: 'Hard — discard all changes',
  discardAllConfirmTitle: 'Discard ALL uncommitted changes?',
  discardAllConfirmMessage:
    "All changes (including staged ones) will be dropped; untracked files are moved to Thaigit's trash. You can click “Undo” right after.",
  discardAll: 'Discard all',
  discardAllTitle: 'Discard all changes',
  discardedAll: 'All changes discarded',
  undoDiscardAll: 'Undo discard all',
  useOperationBanner: (title: string) => `${title} — use the “Abort” button on the operation bar`,
  ignoreTitle: 'Add to .gitignore',
  ignored: (pattern: string) => `Added “${pattern}” to .gitignore`,

  continueOperation: 'Continue',
  skipOperation: 'Skip this commit',
  abortOperation: 'Abort',
  continueTitle: (name: string) => `Continue ${name}`,
  continued: 'Continued',
  conflictsLeft: (count: number) => `${count} conflicted ${count === 1 ? 'file' : 'files'} still unresolved`,
  abortConfirmTitle: (name: string) => `Abort ${name}?`,
  abortConfirmMessage: (name: string) =>
    `The repository will go back to how it was before the ${name} started.`,
  abortTitle: (name: string) => `Abort ${name}`,
  aborted: (name: string) => `Aborted ${name}`,
  skipTitle: 'Skip the current commit',

  createTagTitle: 'Create tag',
  createTagMessage: (label: string) => `The tag points at commit ${label}.`,
  tagNameLabel: 'Tag name',
  tagMessageLabel: 'Message (creates an annotated tag if set)',
  tagPushToRemote: (remote: string) => `Push tag to ${remote}`,
  createTag: 'Create tag',
  tagNameRequired: 'Enter a tag name',
  tagNameInvalid: 'Invalid tag name',
  tagExists: (name: string) => `Tag ${name} already exists`,
  createTagRunning: (name: string) => `Create tag ${name}`,
  tagCreated: (name: string) => `Created tag ${name}`,
  tagCreatedPushed: (name: string) => `Created and pushed tag ${name}`,
  deleteTagConfirmTitle: (name: string) => `Delete tag “${name}”?`,
  deleteTagConfirmMessage: 'Only deletes the tag on your computer. You can click “Undo” right after.',
  deleteTag: 'Delete tag',
  deleteTagRunning: (name: string) => `Delete tag ${name}`,
  tagDeleted: (name: string) => `Deleted tag ${name}`,
  restoreTag: 'Restore tag',
  pushTagRunning: (name: string) => `Push tag ${name}`,
  tagPushed: (name: string, remote: string) => `Pushed tag ${name} to ${remote}`,
  deleteRemoteTagConfirmTitle: (name: string, remote: string) => `Delete tag “${name}” on ${remote}?`,
  deleteRemoteTagConfirmMessage:
    'The tag will be deleted from the remote for everyone; your local tag stays.',
  deleteRemoteTagRunning: 'Delete tag on remote',
  remoteTagDeleted: (name: string, remote: string) => `Deleted tag ${name} on ${remote}`,

  conflictBlocks: (count: number) => `${count} ${count === 1 ? 'conflict' : 'conflicts'}`,
  conflictLegend:
    '“Current” is the version on the current branch (HEAD), “Incoming” is the version being brought in.',
  useAllCurrent: 'Use all Current',
  useAllIncoming: 'Use all Incoming',
  useCurrentRunning: 'Use Current version',
  useIncomingRunning: 'Use Incoming version',
  conflictResolved: (name: string) => `Resolved ${name}`,
  conflictNumber: (index: number, total: number) => `Conflict ${index}/${total}`,
  conflictChosen: 'Chosen',
  keepCurrent: 'Keep Current',
  keepIncoming: 'Keep Incoming',
  keepBoth: 'Keep both',
  keepBothIncomingFirst: 'Both (Incoming first)',
  keepBase: 'Original (base)',
  keepNeither: 'Keep neither',
  clearChoice: 'Clear choice',
  moreChoices: 'More choices',
  current: 'Current',
  incoming: 'Incoming',
  result: 'Result',
  resultEmpty: '(empty — this block will be removed)',
  unchangedLines: (count: number) => `… ${count} unchanged ${count === 1 ? 'line' : 'lines'} — click to show`,
  chosenCount: (chosen: number, total: number) => `${chosen}/${total} chosen`,
  resetChoices: 'Start over',
  saveResolution: 'Save & mark resolved',
  saveResolutionRunning: 'Save resolved file',
  unresolvedBlocks: 'Some conflicts have no resolution chosen yet',
  changedOnDisk: 'The file was changed outside Thaigit — reloaded, please choose again',
  markResolved: 'Mark resolved',
  markResolvedRunning: 'Mark resolved',
  wholeFileOnly: (description: string) => `${description} — only the whole file can be chosen.`,
  notUtf8:
    'The file is not UTF-8, so it cannot be resolved block by block in the app. Choose the whole file, or edit it in an editor and click “Mark resolved”.',
  openConflict: 'Resolve conflict',
  conflictKinds: {
    bothModified: 'Both sides modified',
    bothAdded: 'Both sides added',
    deletedByUs: 'Deleted on the current side',
    deletedByThem: 'Deleted on the other side',
    addedByUs: 'Added on the current side',
    addedByThem: 'Added on the other side',
    bothDeleted: 'Both sides deleted',
    unknown: 'Conflict',
  },

  menuPull: 'Pull',
  menuPush: 'Push',
  menuCheckout: (name: string) => `Checkout ${name}`,
  menuMergeInto: (source: string, target: string) => `Merge ${source} into ${target}`,
  menuRebaseOnto: (branch: string, onto: string) => `Rebase ${branch} onto ${onto}`,
  menuPushBranch: (name: string) => `Push ${name}`,
  menuFastForward: (upstream: string) => `Fast-forward to ${upstream}`,
  menuCreateBranchFrom: (name: string) => `Create branch from ${name}…`,
  menuRename: 'Rename…',
  menuDeleteBranch: 'Delete branch…',
  menuDeleteOnRemote: 'Delete on remote…',
  menuCheckoutTag: (name: string) => `Checkout tag ${name}`,
  menuPushTag: 'Push tag to remote',
  menuCreateBranchFromTag: 'Create branch from tag…',
  menuDeleteTag: 'Delete tag…',
  menuDeleteRemoteTag: 'Delete tag on remote…',
  menuCopyName: 'Copy name',
  copyNameLabel: 'name',
  menuCreateBranchHere: 'Create branch here…',
  menuCreateTagHere: 'Create tag here…',
  menuCheckoutCommit: 'Checkout this commit',
  commitLabel: (sha: string) => `commit ${sha}`,
  menuCherryPick: (branch: string) => `Cherry-pick into ${branch}`,
  menuRevert: 'Revert this commit…',
  menuReset: (branch: string) => `Reset ${branch} to here`,
  menuCopySha: 'Copy SHA',
  menuCopyMessage: 'Copy message',
  copyMessageLabel: 'message',
  menuStageAll: 'Stage all',
  menuUnstageAll: 'Unstage all',
  menuStashAll: 'Stash all changes',
  menuDiscardAll: 'Discard all changes…',
  menuStageFile: 'Stage file',
  menuUnstageFile: 'Unstage file',
  menuDiscardFile: 'Discard changes…',
  menuIgnore: 'Add to .gitignore',
  menuIgnoreFile: 'Ignore this file',
  menuIgnoreExtension: (ext: string) => `Ignore all *.${ext} files`,
  menuIgnoreFolder: (folder: string) => `Ignore folder ${folder}/`,
  menuOpenDiff: 'View diff',
  menuCopyPath: 'Copy path',
  copyPathLabel: 'path',
  menuOpenInEditor: 'Open in editor',
  menuReveal: 'Show in folder',
  menuOpenTerminal: 'Open Terminal in repository',
  menuOpenRepoInEditor: 'Open repository in editor',
  menuRevealRepo: 'Open repository folder',
  osFailed: "Couldn't open the application",
};
