/**
 * Chuỗi giao diện "khung" (cửa sổ repo, graph, sidebar, inspector, thời gian, lỗi, toast, hộp thoại/menu dùng chung). Mỗi gói
 * tính năng có file riêng (`staging`, `branches`, `remote`, `update`) và được `strings.vi.ts` gộp lại — xem file đó.
 * Hàm nhận tham số cho chuỗi có số/tên. Văn phong bám theo app Swift (`Sources/Nhanh`).
 */
export const shell = {
  appName: 'Thaigit',

  welcome: {
    tagline: 'Git client trực quan, miễn phí — graph nhiều màu, thao tác bằng chuột.',
    openFolder: 'Mở thư mục…',
    opening: 'Đang mở…',
    recent: 'Gần đây',
    recentEmpty: 'Chưa mở repo nào gần đây.',
    forget: 'Xoá khỏi danh sách',
    loadRecentFailed: 'Không đọc được danh sách repo gần đây',
    openFailed: 'Không mở được repo',
    notInTauri: 'Đang chạy ngoài ứng dụng Thaigit (không có lõi Rust) nên chưa mở được repo.',
    forgetMissing: 'Xoá khỏi danh sách',
    newWindow: 'Cửa sổ mới',
    newWindowFailed: 'Không mở được cửa sổ mới',
    clone: 'Clone…',
    init: 'Tạo repo mới…',
    cloneTitle: 'Clone repository',
    cloneUrl: 'Địa chỉ repository (HTTPS hoặc SSH)',
    cloneUrlPlaceholder: 'https://github.com/ten/repo.git',
    cloneHost: (host: string, path: string) => (path ? `${host} · ${path}` : host),
    cloneLocalFolder: 'thư mục trên máy',
    cloneDangerous: 'Địa chỉ này có thể chạy lệnh trên máy nên Thaigit không clone.',
    cloneInvalid: 'Chưa nhận ra địa chỉ repository.',
    cloneCredentials:
      'Địa chỉ có chứa mật khẩu / token — nó sẽ nằm nguyên trong .git/config của repo. Nên dùng địa chỉ không kèm token.',
    cloneFolder: 'Đặt trong thư mục',
    cloneFolderPick: 'Chọn thư mục…',
    cloneFolderNone: 'Chưa chọn',
    cloneName: 'Tên thư mục repo',
    cloneInvalidName: 'Tên thư mục không được chứa / \\ : * ? " < > | và không được là . hoặc ..',
    cloneStart: 'Clone',
    cloneCancel: 'Huỷ',
    cloneClose: 'Đóng',
    cloneRunning: 'Đang clone…',
    cloneFailed: 'Không clone được repository',
    initTitle: 'Tạo repo mới',
    initMessage: (folder: string) => `Repo mới sẽ nằm trong ${folder}.`,
    initName: 'Tên thư mục repo',
    initConfirm: 'Tạo repo',
    initFailed: 'Không tạo được repo',
  },

  trust: {
    title: 'Tin tưởng repo này?',
    lead: 'Repo có cấu hình hoặc hook có thể chạy lệnh trên máy bạn. Thaigit chưa chạy gì cả — chỉ tiếp tục khi bạn tin nguồn của repo.',
    findings: 'Đã tìm thấy',
    trust: 'Tin tưởng repo',
    cancel: 'Huỷ',
    failed: 'Không ghi nhận được việc tin tưởng repo',
    changed: 'Cấu hình repo vừa thay đổi — hãy xem lại danh sách trước khi tin tưởng.',
  },

  window: {
    profile: 'Profile — tên & email Git, tài khoản, cài đặt',
    settingsTip: 'Cài đặt',
    identityMissing: 'Chưa đặt tên & email Git',
    identityEdit: 'Đổi tên & email Git…',
    identityAccount: 'Tài khoản GitHub / GitLab cho repo này…',
    identityTitle: 'Tên & email Git',
    identityMessage: 'Tên & email này được ghi vào mọi commit bạn tạo.',
    identitySave: 'Lưu',
    identityName: 'Tên',
    identityEmail: 'Email',
    identityScope: 'Áp dụng cho',
    identityLocal: 'Chỉ repo này',
    identityGlobal: 'Mọi repo trên máy (global)',
    identityNeedName: 'Nhập tên',
    identityBadEmail: 'Email chưa đúng',
    identitySaved: (name: string, email: string) => `Commit giờ dùng ${name} <${email}>`,
    uncommitted: (count: number) => `${count} file chưa commit`,
    uncommittedTip: 'Xem thay đổi chưa commit để stage và commit',
    resizeSidebar: 'Kéo để đổi độ rộng thanh bên',
    resizeInspector: 'Kéo để đổi độ rộng panel chi tiết',
    operationConflicts: (count: number) => `Còn ${count} file xung đột`,
    operationResolved: 'Đã giải quyết hết xung đột',
    toggleSidebar: 'Ẩn/hiện thanh bên',
    toggleInspector: 'Ẩn/hiện panel chi tiết',
    closeRepo: 'Đóng repo (về màn hình chính)',
    detachedHead: (sha: string) => `Detached HEAD @ ${sha}`,
    noBranch: '—',
    branchLabel: 'Nhánh hiện tại',
  },

  graph: {
    searchPlaceholder: 'Tìm commit: tiêu đề, tác giả, SHA, nhánh…',
    searchNone: 'Không tìm thấy commit nào',
    searchCount: (count: number) => `${count} commit khớp`,
    searchPrevious: 'Kết quả trước (Shift + Enter)',
    searchNext: 'Kết quả sau (Enter)',
    searchClose: 'Đóng tìm kiếm (Esc)',
    search: 'Tìm commit',
    columns: {
      refs: 'Nhánh / Tag',
      graph: 'Graph',
      message: 'Commit',
      author: 'Tác giả',
      date: 'Thời gian',
      sha: 'SHA',
    },
    resizeColumn: (title: string) => `Kéo để đổi độ rộng cột ${title}`,
    loading: 'Đang tải lịch sử…',
    loadingMore: 'Đang tải thêm commit…',
    emptyTitle: 'Chưa có commit nào',
    emptyHint: 'Thêm file vào thư mục repository, sau đó stage và tạo commit đầu tiên ở panel bên phải.',
    wip: '// WIP',
    wipTooltip: 'Thay đổi chưa commit — bấm để xem',
    ariaLabel: 'Lịch sử commit',
    pillMore: (count: number) => `+${count}`,
    hideOnGraph: 'Ẩn khỏi graph',
    showOnGraph: 'Hiện lại trên graph',
    solo: 'Chỉ hiện nhánh này (solo)',
    unsolo: 'Bỏ khỏi nhóm chỉ hiện (solo)',
    showAll: 'Hiện tất cả nhánh',
    cannotHideCurrent: 'Không ẩn được nhánh đang checkout',
    hidden: (name: string) => `Đã ẩn ${name} khỏi graph`,
    hiddenSummary: (count: number) => `Đang ẩn ${count} nhánh`,
    soloSummary: (count: number) => `Chỉ hiện ${count} nhánh (và nhánh đang checkout)`,
    moreTitle: (count: number) => `${count} nhánh / tag trên commit này`,
    moreHint: 'Bấm để checkout / merge…',
    pillAuthor: (name: string, email: string, time: string) => `${name} <${email}>\n${time}`,
    detachedHeadPill: 'HEAD (detached)',
    localBranchTip: (name: string, upstream: string | null) =>
      `Nhánh local: ${name}${upstream === null ? '' : ` → ${upstream}`}`,
    remoteBranchTip: (name: string) => `Nhánh remote: ${name}`,
    tagTip: (name: string) => `Tag: ${name}`,
    annotatedTagTip: (name: string) => `Annotated tag: ${name}`,
    wipConflicts: (count: number) => `⚠︎ ${count} xung đột`,
    wipModified: (count: number) => `✎ ${count} file sửa`,
    wipUntracked: (count: number) => `＋ ${count} file mới`,
    wipStaged: (count: number) => `● ${count} đã stage`,
    notLoaded: (sha: string, limit: number) => `Commit ${sha} nằm ngoài ${limit} commit đã tải`,
    loadMore: 'Tải thêm',
  },

  sidebar: {
    filterPlaceholder: 'Lọc nhánh, tag…',
    filterClear: 'Xoá bộ lọc',
    local: 'LOCAL',
    remote: 'REMOTE',
    tags: 'TAGS',
    stashes: 'STASHES',
    noLocal: 'Chưa có nhánh nào',
    noLocalMatch: 'Không có nhánh khớp',
    noRemote: 'Chưa có remote nào',
    noTags: 'Không có tag',
    noTagsMatch: 'Không có tag khớp',
    noStashes: 'Không có stash',
    showMore: (shown: number, noun: string, remaining: number) =>
      `Hiện thêm ${shown} ${noun} (còn ${remaining})`,
    nounBranch: 'nhánh',
    nounTag: 'tag',
    nounStash: 'stash',
    upstreamGone: 'Nhánh trên remote đã bị xoá',
    aheadTip: (count: number) => `${count} commit chưa push`,
    behindTip: (count: number) => `${count} commit mới trên remote chưa pull`,
    annotatedTag: 'Annotated tag',
    tag: 'Tag',
    stashFrom: (branch: string) => `Nhánh: ${branch}`,
    stashNoMessage: '(không có message)',
    stashWip: (branch: string, subject: string) => `WIP trên ${branch}: ${subject}`,
    section: (title: string) => `Mở/đóng mục ${title}`,
    ariaLabel: 'Nhánh, tag và stash',
  },

  inspector: {
    uncommittedBanner: (count: number) => `${count} file chưa commit`,
    uncommittedOn: (branch: string) => `trên ${branch}`,
    uncommittedStageAll: 'Stage tất cả',
    uncommittedReview: 'Xem & commit',
    uncommittedReviewTip: 'Mở danh sách file chưa commit để stage, bỏ stage, huỷ và commit',
    ariaLabel: 'Chi tiết',
    emptyTitle: 'Chọn một commit',
    emptyHint:
      'Bấm vào một commit trên graph để xem chi tiết, hoặc chọn dòng “WIP” để xem thay đổi chưa commit.',
    loadingDetails: 'Đang tải chi tiết…',
    noDetails: 'Không có chi tiết',
    commit: 'commit',
    parent: 'parent',
    parentTip: 'Tới commit parent',
    copySha: 'Sao chép SHA đầy đủ',
    copied: (label: string) => `Đã sao chép ${label}`,
    copyFailed: 'Không sao chép được',
    committedBy: (name: string, when: string) => `Commit bởi ${name} · ${when}`,
    showFullBody: 'Xem toàn bộ mô tả',
    collapseBody: 'Thu gọn',
    filesChanged: (count: number) => `${count} file thay đổi`,
    noFiles: 'Không có file nào thay đổi (commit rỗng hoặc merge).',
    stash: 'Stash',
    stashMissing: 'Stash không còn tồn tại',
    stashFromBranch: (branch: string) => `Từ nhánh ${branch}`,
    stashActionsLater: 'Apply / Pop / Xoá sẽ có ở bản sau.',
    wipTitle: 'Thay đổi chưa commit',
    wipPlaceholder:
      'Stage từng file/hunk/dòng và tạo commit sẽ có ở bản sau (giai đoạn 5). Đây mới là danh sách chỉ-đọc.',
    wipUnstaged: 'Chưa stage',
    wipStaged: 'Đã stage',
    wipConflicts: 'Xung đột',
    wipClean: 'Không có thay đổi nào.',
    changeKind: {
      added: 'Thêm mới',
      untracked: 'File mới (chưa track)',
      modified: 'Đã sửa',
      deleted: 'Đã xoá',
      renamed: 'Đổi tên',
      copied: 'Copy',
      typeChanged: 'Đổi loại file',
      conflicted: 'Xung đột',
      unknown: 'Khác',
    },
  },

  time: {
    justNow: 'vừa xong',
    minutes: (count: number) => `${count} phút`,
    hours: (count: number) => `${count} giờ`,
    days: (count: number) => `${count} ngày`,
    weeks: (count: number) => `${count} tuần`,
    months: (count: number) => `${count} tháng`,
    years: (count: number) => `${count} năm`,
    ago: (span: string) => `${span} trước`,
    inFuture: (span: string) => `sau ${span}`,
  },

  errors: {
    status: 'Không đọc được trạng thái repository',
    refs: 'Không đọc được nhánh và tag',
    history: 'Không tải được lịch sử commit',
    commitDetails: 'Không tải được chi tiết commit',
    stashDetails: 'Không tải được nội dung stash',
    watch: 'Không theo dõi được thay đổi của repo (phải bấm làm mới thủ công)',
    repoMissing: 'Không tìm thấy thư mục repository',
    repoUntrusted: 'Cấu hình repo vừa thay đổi — Thaigit tạm dừng chạy lệnh cho tới khi bạn xem lại.',
    reviewTrust: 'Xem lại cấu hình repo',
    cancelled: (title: string) => `Đã huỷ: ${title}`,
    unexpectedTitle: 'Đã xảy ra lỗi',
    crashTitle: 'Màn hình này gặp lỗi',
    crashMessage:
      'Thaigit đã dừng phần giao diện bị lỗi để không ảnh hưởng tới repository của bạn. Dữ liệu không bị thay đổi.',
    crashRetry: 'Thử lại',
    crashHome: 'Về màn hình chính',
    /** Câu thân thiện thay cho lỗi thô (errors/friendly.ts) — không bao giờ hiện stderr / message gốc / stack trace. */
    friendly: {
      unexpected: 'Đã xảy ra lỗi không mong muốn. Hãy thử lại; nếu vẫn lỗi, khởi động lại Thaigit.',
      cancelled: 'Thao tác đã được huỷ.',
      gitFailed:
        'Git không thực hiện được thao tác này. Xem chi tiết trong “Nhật ký lệnh git” (menu Thêm ⋯).',
      policy: 'Thaigit chặn lệnh này vì lý do an toàn.',
      notFound: 'Không tìm thấy file hoặc thư mục cần dùng — có thể nó đã bị xoá hoặc đổi tên.',
      outOfScope: 'Đường dẫn nằm ngoài repository nên Thaigit không truy cập.',
      conflict: 'Nội dung vừa thay đổi ở nơi khác hoặc đã tồn tại — hãy tải lại rồi thử lại.',
      busy: 'Repository đang bận với một thao tác khác — thử lại sau giây lát.',
      io: 'Không đọc / ghi được dữ liệu trên máy — kiểm tra quyền truy cập và dung lượng ổ đĩa.',
      gitMissing: 'Không tìm thấy git trên máy — hãy cài Git (Windows: Git for Windows) rồi mở lại Thaigit.',
      lfsMissing: 'Máy chưa cài Git LFS — hãy cài Git LFS (git-lfs.com) rồi thử lại.',
      lfsServer: 'Máy chủ Git LFS báo lỗi hoặc thiếu file LFS — xem chi tiết trong Nhật ký lệnh git.',
      gitTooOld: 'Phiên bản git trên máy quá cũ — hãy cập nhật git.',
      untrusted: 'Repository chưa được tin tưởng nên Thaigit không chạy lệnh này.',
      notARepository: 'Thư mục này không phải repository git.',
      bareRepository: 'Đây là bare repository (không có working tree) nên không mở được.',
      invalidName: 'Tên không hợp lệ.',
      auth: 'Remote từ chối đăng nhập — kiểm tra tài khoản / token rồi thử lại.',
      network: 'Không kết nối được tới remote — kiểm tra mạng rồi thử lại.',
      remoteMissing: 'Không tìm thấy repository trên remote — sai địa chỉ hoặc tài khoản không có quyền.',
      lockFile:
        'Một tiến trình git khác đang chạy trong repository (file khoá .lock) — đợi nó xong rồi thử lại.',
      gitConflict: 'Có xung đột cần giải quyết trước.',
      localChanges: 'Có thay đổi chưa commit chặn thao tác này — commit hoặc stash trước.',
      notMerged: 'Nhánh có commit chưa được merge.',
      rejected: 'Remote có commit mới mà máy bạn chưa có — hãy pull trước.',
      diverged: 'Nhánh local và remote đã diverge — mỗi bên có commit mà bên kia chưa có.',
      noUpstream: 'Nhánh chưa có upstream trên remote.',
      nothingToCommit: 'Không có gì để commit.',
      alreadyExists: 'Tên này đã tồn tại.',
      unknownRef: 'Không tìm thấy nhánh, commit hoặc file được chỉ định.',
      permission: 'Không có quyền truy cập file hoặc thư mục.',
      diskFull: 'Ổ đĩa đã đầy.',
      identity:
        'Chưa đặt tên và email cho git — chạy git config --global user.name / user.email rồi thử lại.',
      signing: 'Không ký được commit — kiểm tra cấu hình khoá GPG / SSH.',
      hook: 'Hook của repository đã từ chối thao tác này.',
    },
  },

  toast: {
    dismiss: 'Đóng thông báo',
    expand: 'Xem đầy đủ',
    collapse: 'Thu gọn',
  },

  /** Vùng giữa của cửa sổ repo khi không phải graph (diff, trình giải conflict). */
  center: {
    backToGraph: 'Về graph',
  },

  /** Hộp thoại dùng chung (ConfirmDialog, DialogPanel). */
  dialog: {
    confirm: 'Đồng ý',
    cancel: 'Huỷ',
    close: 'Đóng',
  },

  /** Menu ngữ cảnh HTML (ContextMenu). */
  menu: {
    ariaLabel: 'Menu ngữ cảnh',
    actionFailed: 'Không thực hiện được thao tác',
  },

  /** Thanh tiến độ thao tác (BusyBar). */
  busy: {
    cancel: 'Huỷ',
    cancelTip: 'Huỷ thao tác đang chạy',
  },
} as const;
