/** Bản tiếng Anh của `shell.vi.ts` (cùng khoá, cùng tham số). */
import type { shell as source } from './shell.vi.ts';
import type { Translation } from './types.ts';

export const shell: Translation<typeof source> = {
  appName: 'Thaigit',

  welcome: {
    tagline: 'A free, visual Git client — colorful graph, everything with the mouse.',
    openFolder: 'Open folder…',
    opening: 'Opening…',
    recent: 'Recent',
    recentEmpty: 'No recently opened repositories.',
    forget: 'Remove from list',
    loadRecentFailed: "Couldn't read the recent repositories",
    openFailed: "Couldn't open the repository",
    notInTauri: 'Running outside the Thaigit app (no Rust core), so repositories cannot be opened.',
    forgetMissing: 'Remove from list',
    newWindow: 'New window',
    newWindowFailed: "Couldn't open a new window",
    clone: 'Clone…',
    init: 'New repository…',
    cloneTitle: 'Clone repository',
    cloneUrl: 'Repository address (HTTPS or SSH)',
    cloneUrlPlaceholder: 'https://github.com/name/repo.git',
    cloneHost: (host: string, path: string) => (path ? `${host} · ${path}` : host),
    cloneLocalFolder: 'local folder',
    cloneDangerous: 'This address can run commands on your computer, so Thaigit will not clone it.',
    cloneInvalid: 'Not a recognized repository address yet.',
    cloneCredentials:
      "The address contains a password / token — it will stay in the repository's .git/config. Prefer an address without a token.",
    cloneFolder: 'Put it in folder',
    cloneFolderPick: 'Choose folder…',
    cloneFolderNone: 'Not chosen',
    cloneName: 'Repository folder name',
    cloneInvalidName: 'The folder name cannot contain / \\ : * ? " < > | and cannot be . or ..',
    cloneStart: 'Clone',
    cloneCancel: 'Cancel',
    cloneClose: 'Close',
    cloneRunning: 'Cloning…',
    cloneFailed: "Couldn't clone the repository",
    initTitle: 'New repository',
    initMessage: (folder: string) => `The new repository will be created in ${folder}.`,
    initName: 'Repository folder name',
    initConfirm: 'Create repository',
    initFailed: "Couldn't create the repository",
  },

  trust: {
    title: 'Trust this repository?',
    lead: 'This repository has configuration or hooks that can run commands on your computer. Thaigit has not run anything yet — only continue if you trust where it came from.',
    findings: 'Found',
    trust: 'Trust repository',
    cancel: 'Cancel',
    failed: "Couldn't record that you trust this repository",
    changed: 'The repository configuration just changed — review the list again before trusting it.',
  },

  window: {
    uncommitted: (count: number) => `${count} uncommitted ${count === 1 ? 'file' : 'files'}`,
    uncommittedTip: 'Show uncommitted changes to stage and commit',
    resizeSidebar: 'Drag to resize the sidebar',
    resizeInspector: 'Drag to resize the details panel',
    operationConflicts: (count: number) => `${count} ${count === 1 ? 'file' : 'files'} still in conflict`,
    operationResolved: 'All conflicts resolved',
    toggleSidebar: 'Show/hide sidebar',
    toggleInspector: 'Show/hide details panel',
    closeRepo: 'Close repository (back to the start screen)',
    detachedHead: (sha: string) => `Detached HEAD @ ${sha}`,
    noBranch: '—',
    branchLabel: 'Current branch',
  },

  graph: {
    searchPlaceholder: 'Find commits: subject, author, SHA, branch…',
    searchNone: 'No matching commits',
    searchCount: (count: number) => `${count} matching ${count === 1 ? 'commit' : 'commits'}`,
    searchPrevious: 'Previous result (Shift + Enter)',
    searchNext: 'Next result (Enter)',
    searchClose: 'Close search (Esc)',
    search: 'Find commits',
    columns: {
      refs: 'Branch / Tag',
      graph: 'Graph',
      message: 'Commit',
      author: 'Author',
      date: 'Date',
      sha: 'SHA',
    },
    resizeColumn: (title: string) => `Drag to resize the ${title} column`,
    loading: 'Loading history…',
    loadingMore: 'Loading more commits…',
    emptyTitle: 'No commits yet',
    emptyHint:
      'Add files to the repository folder, then stage them and create the first commit in the right panel.',
    wip: '// WIP',
    wipTooltip: 'Uncommitted changes — click to view',
    ariaLabel: 'Commit history',
    pillMore: (count: number) => `+${count}`,
    moreTitle: (count: number) =>
      `${count} ${count === 1 ? 'branch / tag' : 'branches / tags'} on this commit`,
    moreHint: 'Click to check out / merge…',
    pillAuthor: (name: string, email: string, time: string) => `${name} <${email}>\n${time}`,
    detachedHeadPill: 'HEAD (detached)',
    localBranchTip: (name: string, upstream: string | null) =>
      `Local branch: ${name}${upstream === null ? '' : ` → ${upstream}`}`,
    remoteBranchTip: (name: string) => `Remote branch: ${name}`,
    tagTip: (name: string) => `Tag: ${name}`,
    annotatedTagTip: (name: string) => `Annotated tag: ${name}`,
    wipConflicts: (count: number) => `⚠︎ ${count} ${count === 1 ? 'conflict' : 'conflicts'}`,
    wipModified: (count: number) => `✎ ${count} modified`,
    wipUntracked: (count: number) => `＋ ${count} new`,
    wipStaged: (count: number) => `● ${count} staged`,
    notLoaded: (sha: string, limit: number) => `Commit ${sha} is outside the ${limit} loaded commits`,
    loadMore: 'Load more',
  },

  sidebar: {
    filterPlaceholder: 'Filter branches, tags…',
    filterClear: 'Clear filter',
    local: 'LOCAL',
    remote: 'REMOTE',
    tags: 'TAGS',
    stashes: 'STASHES',
    noLocal: 'No branches yet',
    noLocalMatch: 'No matching branches',
    noRemote: 'No remotes yet',
    noTags: 'No tags',
    noTagsMatch: 'No matching tags',
    noStashes: 'No stashes',
    showMore: (shown: number, noun: string, remaining: number) =>
      `Show ${shown} more ${noun} (${remaining} left)`,
    nounBranch: 'branches',
    nounTag: 'tags',
    nounStash: 'stashes',
    upstreamGone: 'The remote branch was deleted',
    aheadTip: (count: number) => `${count} ${count === 1 ? 'commit' : 'commits'} not pushed yet`,
    behindTip: (count: number) =>
      `${count} new ${count === 1 ? 'commit' : 'commits'} on the remote not pulled yet`,
    annotatedTag: 'Annotated tag',
    tag: 'Tag',
    stashFrom: (branch: string) => `Branch: ${branch}`,
    stashNoMessage: '(no message)',
    stashWip: (branch: string, subject: string) => `WIP on ${branch}: ${subject}`,
    section: (title: string) => `Expand/collapse ${title}`,
    ariaLabel: 'Branches, tags and stashes',
  },

  inspector: {
    uncommittedBanner: (count: number) => `${count} uncommitted ${count === 1 ? 'file' : 'files'}`,
    uncommittedOn: (branch: string) => `on ${branch}`,
    uncommittedStageAll: 'Stage All',
    uncommittedReview: 'Review & Commit',
    uncommittedReviewTip: 'Open the uncommitted files to stage, unstage, discard and commit',
    ariaLabel: 'Details',
    emptyTitle: 'Select a commit',
    emptyHint: 'Click a commit in the graph to see its details, or the “WIP” row to see uncommitted changes.',
    loadingDetails: 'Loading details…',
    noDetails: 'No details',
    commit: 'commit',
    parent: 'parent',
    parentTip: 'Go to parent commit',
    copySha: 'Copy full SHA',
    copied: (label: string) => `Copied ${label}`,
    copyFailed: "Couldn't copy",
    committedBy: (name: string, when: string) => `Committed by ${name} · ${when}`,
    showFullBody: 'Show full description',
    collapseBody: 'Collapse',
    filesChanged: (count: number) => `${count} ${count === 1 ? 'file' : 'files'} changed`,
    noFiles: 'No files changed (empty commit or merge).',
    stash: 'Stash',
    stashMissing: 'This stash no longer exists',
    stashFromBranch: (branch: string) => `From branch ${branch}`,
    stashActionsLater: 'Apply / Pop / Drop are coming in a later version.',
    wipTitle: 'Uncommitted changes',
    wipPlaceholder:
      'Staging files/hunks/lines and committing are coming in a later version (phase 5). This is a read-only list for now.',
    wipUnstaged: 'Unstaged',
    wipStaged: 'Staged',
    wipConflicts: 'Conflicts',
    wipClean: 'No changes.',
    changeKind: {
      added: 'Added',
      untracked: 'New file (untracked)',
      modified: 'Modified',
      deleted: 'Deleted',
      renamed: 'Renamed',
      copied: 'Copied',
      typeChanged: 'File type changed',
      conflicted: 'Conflict',
      unknown: 'Other',
    },
  },

  time: {
    justNow: 'just now',
    minutes: (count: number) => `${count} ${count === 1 ? 'minute' : 'minutes'}`,
    hours: (count: number) => `${count} ${count === 1 ? 'hour' : 'hours'}`,
    days: (count: number) => `${count} ${count === 1 ? 'day' : 'days'}`,
    weeks: (count: number) => `${count} ${count === 1 ? 'week' : 'weeks'}`,
    months: (count: number) => `${count} ${count === 1 ? 'month' : 'months'}`,
    years: (count: number) => `${count} ${count === 1 ? 'year' : 'years'}`,
    ago: (span: string) => `${span} ago`,
    inFuture: (span: string) => `in ${span}`,
  },

  errors: {
    status: "Couldn't read the repository status",
    refs: "Couldn't read branches and tags",
    history: "Couldn't load the commit history",
    commitDetails: "Couldn't load the commit details",
    stashDetails: "Couldn't load the stash contents",
    watch: "Couldn't watch the repository for changes (refresh manually)",
    repoMissing: 'Repository folder not found',
    repoUntrusted:
      'The repository configuration just changed — Thaigit has paused running commands until you review it.',
    reviewTrust: 'Review repository configuration',
    cancelled: (title: string) => `Cancelled: ${title}`,
    unexpectedTitle: 'Something went wrong',
    crashTitle: 'This screen ran into a problem',
    crashMessage:
      'Thaigit stopped the broken part of the interface so it cannot affect your repository. No data was changed.',
    crashRetry: 'Try again',
    crashHome: 'Back to the start screen',
    friendly: {
      unexpected:
        'Something unexpected went wrong. Please try again; if it keeps happening, restart Thaigit.',
      cancelled: 'The operation was cancelled.',
      gitFailed: 'Git could not complete this operation. See the details in “Git command log” (More ⋯ menu).',
      policy: 'Thaigit blocked this command for safety reasons.',
      notFound: "The file or folder needed wasn't found — it may have been deleted or renamed.",
      outOfScope: 'The path is outside the repository, so Thaigit will not access it.',
      conflict: 'The content just changed elsewhere or already exists — reload and try again.',
      busy: 'The repository is busy with another operation — try again in a moment.',
      io: "Couldn't read / write data on this computer — check permissions and free disk space.",
      gitMissing:
        'Git was not found on this computer — install Git (Windows: Git for Windows) and reopen Thaigit.',
      lfsMissing: "Git LFS isn't installed — install Git LFS (git-lfs.com) and try again.",
      lfsServer:
        'The Git LFS server returned an error or an LFS file is missing — see the git command log for details.',
      gitTooOld: 'The installed git is too old — please update git.',
      untrusted: "The repository isn't trusted yet, so Thaigit won't run this command.",
      notARepository: 'This folder is not a git repository.',
      bareRepository: 'This is a “bare” repository (no working folder), so it cannot be opened.',
      invalidName: 'Invalid name.',
      auth: 'The remote rejected the sign-in — check your account / token and try again.',
      network: "Couldn't connect to the remote — check your network and try again.",
      remoteMissing:
        "Repository not found on the remote — wrong address, or the account doesn't have access.",
      lockFile:
        'Another git process is running in this repository (.lock file) — wait for it to finish and try again.',
      gitConflict: 'There are conflicts to resolve first.',
      localChanges: 'Uncommitted changes are blocking this operation — commit or stash them first.',
      notMerged: 'The branch has commits that are not merged.',
      rejected: "The remote has new commits you don't have yet — pull first.",
      diverged: 'The local and remote branches have diverged.',
      noUpstream: 'The branch has no matching branch on the remote yet.',
      nothingToCommit: 'Nothing to commit.',
      alreadyExists: 'This name already exists.',
      unknownRef: 'The given branch, commit or file was not found.',
      permission: 'No permission to access the file or folder.',
      diskFull: 'The disk is full.',
      identity:
        'Your git name and email are not set — run git config --global user.name / user.email and try again.',
      signing: "Couldn't sign the commit — check your GPG / SSH key configuration.",
      hook: 'A repository hook rejected this operation.',
    },
  },

  toast: {
    dismiss: 'Dismiss notification',
    expand: 'Show all',
    collapse: 'Collapse',
  },

  center: {
    backToGraph: 'Back to graph',
  },

  dialog: {
    confirm: 'OK',
    cancel: 'Cancel',
    close: 'Close',
  },

  menu: {
    ariaLabel: 'Context menu',
    actionFailed: "Couldn't perform the action",
  },

  busy: {
    cancel: 'Cancel',
    cancelTip: 'Cancel the running operation',
  },
};
